#!/usr/bin/env bash
# Run 3 of the lens pilot: the 22 Writebook stage-1 tasks, -k 3, three arms in
# parallel, Haiku 4.5 through OpenRouter so miniswen's cache breakpoints fire.
#
#   bench/lemans/pilot/run3.sh            # launches, watches, writes the readout
#   K=3 C=3 CEILING=55 bench/lemans/pilot/run3.sh
#
# Detach it (nohup/setsid); a full run is ~2-3 h. Trials land in
# <arm>/runs/run3/claude-haiku-4.5/ so the run-2 dirs stay untouched. A
# watchdog kills every arm if spend passes $CEILING or the first five finished
# trials average under 50% cache hit (wrong model string). On completion it
# runs readout.rb, commits the RESULTS draft, pushes, and prints "== done".
set -uo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo="$(cd "$here/../../.." && pwd)"
export PATH="$HOME/.orbstack/bin:$HOME/.local/share/mise/shims:$PATH"
set -a; . "$repo/.env"; set +a
: "${OPENROUTER_API_KEY:?OPENROUTER_API_KEY absent}"

K="${K:-3}"; C="${C:-3}"; CEILING="${CEILING:-55}"; DATE="${DATE:-$(date +%Y-%m-%d)}"
TASKS=(ac-deep-link-return ac-throttle-search aj-enqueue-after-commit aj-resumable-cleanup
  ar-announce-once ar-archive-book-access ar-atomic-import ar-bulk-access-grants
  ar-compact-positions ar-erase-account ar-release-recap ar-tenant-isolation
  as-purge-embedded-images as-variant-processed-once av-toc-cache-per-role hello-world
  hw-scoped-broadcast sec-audit-sweep sup-cache-library-digest sup-legacy-conversions
  sup-log-to-terminal tst-error-page-flake)
ARMS=(baseline lensed vocab)

task_args=(); for t in "${TASKS[@]}"; do task_args+=(--task "$t"); done
echo "== run3 start $(date -u +%FT%TZ) k=$K c=$C ceiling=\$$CEILING tasks=${#TASKS[@]} arms=${ARMS[*]}"

pids=()
for arm in "${ARMS[@]}"; do
  mkdir -p "$here/$arm/runs/run3"
  ( cd "$repo" && exec nice -n 10 lemans run --bench "$here/$arm" --backend docker \
      --runs-dir "$here/$arm/runs/run3" -k "$K" -c "$C" "${task_args[@]}" ) \
      > "$here/$arm/runs/run3/lemans.log" 2>&1 &
  pids+=($!); echo "arm $arm pid $!"
done

spend() { ruby -rjson -e 'puts Dir[ARGV[0]].sum { |f| JSON.parse(File.read(f)).dig("usage","cost_usd").to_f }' "$here/*/runs/run3/*/*/result.json"; }
count() { ls "$here"/*/runs/run3/*/*/result.json 2>/dev/null | wc -l | tr -d ' '; }
hit()   { ruby -rjson -e 'i=c=0; Dir[ARGV[0]].each { |f| u=JSON.parse(File.read(f))["usage"]; i+=u["input_tokens"].to_i; c+=u["cached_tokens"].to_i }; puts i.zero? ? 0 : (100*c/i)' "$here/*/runs/run3/*/*/result.json"; }
alive() { for p in "${pids[@]}"; do kill -0 "$p" 2>/dev/null && return 0; done; return 1; }
killall_arms() { echo "== KILL: $1 $(date -u +%FT%TZ)"; kill "${pids[@]}" 2>/dev/null; sleep 5; kill -9 "${pids[@]}" 2>/dev/null; docker ps -q --filter name=lemans | xargs -r docker rm -f >/dev/null 2>&1; echo "$1" > "$here/run3.KILLED"; }

gate_checked=0
while alive; do
  sleep 120
  n=$(count); s=$(spend); h=$(hit)
  echo "$(date -u +%H:%MZ) trials=$n spend=\$$s cache=${h}%"
  if [ "$gate_checked" = 0 ] && [ "$n" -ge 5 ]; then
    gate_checked=1
    [ "$h" -lt 50 ] && { killall_arms "cache hit ${h}% < 50% on first $n trials"; break; }
  fi
  awk -v s="$s" -v c="$CEILING" 'BEGIN{exit !(s>c)}' && { killall_arms "spend \$$s > \$$CEILING"; break; }
done
wait 2>/dev/null

echo "== runs finished $(date -u +%FT%TZ) trials=$(count) spend=\$$(spend) cache=$(hit)%"
echo "== reach.rb cross-check"
ruby "$here/reach.rb" baseline="$here/baseline/runs/run3" lensed="$here/lensed/runs/run3" vocab="$here/vocab/runs/run3" 2>&1 || true
out="$here/RESULTS-$DATE.md"
ruby "$here/readout.rb" "$DATE" > "$out" && echo "== readout written $out"
cd "$repo" && git add "$out" && git commit -q -m "bench(lemans): run 3 raw readout (auto-generated by run3.sh)" && git push -q -u origin "$(git rev-parse --abbrev-ref HEAD)" && echo "== pushed"
rm -f "$repo/.parked"
echo "== done $(date -u +%FT%TZ)"
